name: My First Workflow
on: 
  push:
jobs:
  echo_the_date:
    runs-on: ubuntu-latest
    steps:
    - name: echo the date
      run : echo "The current time and date is $(date)"
    - name: echo the current branch
      run : echo ${{ github.ref_name}}

  test_and_deploy:
    runs-on: ubuntu-latest
    env:
      OPENWEATHERMAP_KEY: ${{ secrets.openweathermap_api }}
    steps:
    # https://github.com/marketplace/actions/setup-java-jdk
    - name: Setup JDB 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    #https:github.com/marketplace/actions/setup-maven
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.3
      with:
        maven-version: 3.8.2

    #https:github.com/marketplace/actions/
    - name: 